[GENERAL]
PORT = 3001                                 # Port to run the server on
SIMILARITY_MEASURE = "cosine"               # "cosine" or "dot"
KEEP_ALIVE = "5m"                           # How long to keep Ollama models loaded into memory. (Instead of using -1 use "-1m")
GLOBAL_CONTEXT = "research data management" # Context for metasearch (Leave as is)

[API_KEYS]
OPENAI = ""     # OpenAI API key
GROQ = ""       # Groq API key
ANTHROPIC = ""  # Anthropic API key
GEMINI = ""     # Gemini API key

[API_ENDPOINTS]
SEARXNG = "http://localhost:32768"  # SearxNG API URL
OLLAMA = ""                         # Ollama API URL; e.g. http://host.docker.internal:11434